### ISSUE TITLE
Cannot create field in element - nil

### ISSUE THREAD

**Issue by voslartomas** [chidiwilliams/flatbson#4]
Hello, great library thanks for that :)

What about this case, if you have object like this 

```
{
verifyToken: {
  code: string,
  expiresAt: date,
}
}
```

If verify token is pre filled with data, it works fine, but if verifyToken is nil there is an error like this

```
multiple write errors: [{write errors: [{Cannot create field 'code' in element {forgotPasswordToken: null}}]}, {<nil>}]
```

**Comment by kurennoy16** [comment]
Hi guys!
Your library saved a lot of my time, GJ)
Unfortunately, I stuck with the same issue.
@chidiwilliams Did you have a look?

**Comment by voslartomas** [comment]
@kurennoy16 For now I just create object in DB, like this (ie. not setting whole verifyToken to nil)

```
verifyToken: {
 code: nil,
 expiresAt: nil
}
```

Just a workaround, maybe even better practice.

**Comment by kurennoy16** [comment]
Thanks for the advice, @voslartomas 

Another solution, without hardcoded nulls. Just use `bson` tag's attribute `omitempty`
Example
...`
GeoCode           *GeoCode      `bson:"geoCode,omitempty"`
...`

**Comment by chidiwilliams** [comment]
@voslartomas @kurennoy16 Good to hear the library has been helpful, and you've found a workaround for your use-case
