### ISSUE TITLE
Pointer nested pointer serialized to address

### ISSUE THREAD

**Issue by liumq** [chidiwilliams/flatbson#6]
type X struct {
		Y  string  `bson:"y,omitempty"`
		Z  string  `bson:"z,omitempty"`
		ZZ *string `bson:"zz,omitempty"`
	}
	type A struct {
		B *X `bson:"b,omitempty"`
		//F []*X   `bson:"f,omitempty"`
	}
	zz := "zz"
	aaa := X{"aaa", "", &zz}
	flattened, err := flatbson.Flatten(A{
		B: &aaa,
	})

want result: map[b.y:aaa b.zz:zz]
but actual: map[b.y:aaa b.zz:0xc0002b1610]

Is there a problem with my use?

**Comment by chidiwilliams** [comment]
This library only flattens the fields and leaves the actual values untouched. To get the result you want, the struct should hold the concrete value and not a pointer.

```go
type X struct {
	Y  string  `bson:"y,omitempty"`
	Z  string  `bson:"z,omitempty"`
	ZZ string `bson:"zz,omitempty"`
}

zz := "zz"
aaa := X{"aaa", "", zz}
flattened, err := flatbson.Flatten(A{
	B: &aaa,
})
// map[b.y:aaa b.zz:zz]
```

**Comment by timurguseynov** [comment]
Is that would be easy to extend this library so that if the pointer is provided to convert it to value, right?
