### ISSUE TITLE
Arrays - 

### ISSUE THREAD

**Issue by timurguseynov** [chidiwilliams/flatbson#7]
I want to make it work with arrays so that this:

```go
type My struct {
  Arr []string `bson:"arr"`
}

func test() {
	my := My{}
	my.Arr = make([]string, 0, 2)
	my.Arr[1] = "test"
	flatbson.Flatten(my)
}
```

Becomes something like this:

```javascript
{"arr.1": "test"}
```

Do you think that would be easy to do?

Thank you!
Tim

**Comment by chidiwilliams** [comment]
Hi, that's beyond the original scope I had for this library, so I won't be able to add support for this, unfortunately.

**Comment by timurguseynov** [comment]
I want to add it myself. Just want to ask you if that's not a hard thing to do :)
